[project]
name = "calculator"
version = "0.1.0"
description = "simple calculator"
readme = "README.md"
authors = [
    { name = "victoring557", email = "victor.boroswork@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
calculator = "calculator:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
